defaults: &defaults
  android_gcm_url: https://gcm-http.googleapis.com/gcm/send
  fb_graph_me_url: https://graph.facebook.com/me
  app_name: 'Go-Park'
  vat: 0.21
  comision_fixed: 2.5
  comision_percent: 0.08

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults