defaults: &defaults
  short_term_max_range: 1200
  short_term_expiration: 5
  long_term_max_range: 10000
  long_term_expiration: 10

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults