defaults: &defaults
  short_term_expiration: 10 # minutes
  long_term_expiration: 2 # weeks
  android_gcm_url: https://gcm-http.googleapis.com/gcm/send
  fb_debug_token_url: https://graph.facebook.com/debug_token

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults