# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fdee5f654bf33d0efd51e3099ba6fa4c
  google_api_key: <%= ENV["GOOGLE_API_KEY"] %>
  fb_app_secret: <%= ENV["FB_APP_SECRET"] %>
  sms_auth_token: <%= ENV["SMS_AUTH"] %>

test:
  secret_key_base: 72b4952a51430913b1f68f42f6376cfb
  google_api_key: <%= ENV["GOOGLE_API_KEY"] %>
  fb_app_secret: <%= ENV["FB_APP_SECRET"] %>
  sms_auth_token: <%= ENV["SMS_AUTH"] %>


# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  google_api_key: <%= ENV["GOOGLE_API_KEY"] %>
  fb_app_secret: <%= ENV["FB_APP_SECRET"] %>
  sms_auth_token: <%= ENV["SMS_AUTH"] %>


